version: '3'

services:
  #MYSQL
  mariadb:
    image: mariadb
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpfpm:
      build: ./build/php-fpm
      image: php:7.0-fpm
      ports:
          - "9000:9000"
      volumes:
          - ${PWD-/home/gustavo/workspace/environments/docker-magento2}/php/php.ini:/usr/local/etc/php/conf.d/php.ini
          - ./public:/usr/share/nginx/html
      environment:
        XDEBUG: "true"
  nginx:
    depends_on:
      - phpfpm
    image: nginx
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        - ${PWD-/home/gustavo/workspace/environments/docker-magento2}/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/sites-available:/etc/nginx/sites-available/
        - ./nginx/sites-enable:/etc/nginx/sites-enable/
        - ./public:/usr/share/nginx/html
        - ./logs:/usr/share/nginx/log
